# Generated by Django 4.1.7 on 2024-12-06 03:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0003_alter_productimage_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productimage",
            name="alt_text",
            field=models.CharField(
                blank=True, help_text="product images", max_length=255
            ),
        ),
    ]
